version: "2"
plugins:
  eslint:
    enabled:  true
    config:
      config: .eslintrc.json
      extensions:
        - .js
        - .ts
checks:
  argument-count:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 80
  similar-code:
    enabled: false  
  identical-code:
    enabled: false
